### ISSUE TITLE
建议把Textfiled暴露出来

### ISSUE THREAD

**Issue by MasterBetter** [ZPP506/ZPTextAttribiteFild#1]
#import "ZPTextAttribiteBaseVrify.h"

@interface ZPTextAttribiteFild : UIControl
/// placeHold 和 输入框的间距
@property (nonatomic, assign) CGFloat placeHoldSpaceFild;
 

@property (nonatomic, strong) UITextField *textField;

**Comment by MasterBetter** [comment]
最后一行暴露出来还是比较好的。这样子就可以跟RAC配合使用了

**Comment by ZPP506** [comment]
如果暴露出来将不满足装饰模式的设计思想 - （不过业务为先， 可以自行 fork）

**Comment by MasterBetter** [comment]
我是配合RAC使用的，我自己把这个调整了，效果写得很好。你的代码将用在一个大项目中

**Comment by MasterBetter** [comment]
能不能增加一个小功能，如果是输入密码之类，需要明文和暗文切换

**Comment by ZPP506** [comment]
OK 已经添加

**Comment by MasterBetter** [comment]
我给你发邮件了，到你的qq邮箱，你看下
